name: CI Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build python project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/scalable-course/fastapi-example:${{ github.sha }}
        push: true
  deploy:
    name: Deploy to VM
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to VM
      run: |
        docker pull ghcr.io/scalable-course/fastapi-example:${{ github.sha }}
        docker stop fastapi-example || true
        docker rm fastapi-example || true
        docker run -d --name fastapi-example -p 80:8000 ghcr.io/scalable-course/fastapi-example:${{ github.sha }}
