name: CI Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build python project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        tags: scalable-course/fastapi-example:latest
        push: false
